#!/bin/bash

# Define the number of parallel processes
NUM_PROCESSES=5

# Function to process a URL
process_url() {
    local url="$1"
    curl -k -v "$url" --proxy http://127.0.0.1:8080
}

# Read each line from stdin and process in parallel
while IFS= read -r url; do
    # Launch a new process to handle each URL
    process_url "$url" &
    
    # Limit the number of parallel processes
    while (( $(jobs -p | wc -l) >= NUM_PROCESSES )); do
        sleep 1
    done
done

# Wait for all processes to finish
wait
